sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t felipeamendes/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true felipeamendes/react-test npm test

after_success:
  - docker build -t felipeamendes/multi-client ./client
  - docker build -t felipeamendes/multi-nginx ./nginx
  - docker build -t felipeamendes/multi-server ./server
  - docker build -t felipeamendes/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push images to docker hub
  - docker push felipeamendes/multi-client
  - docker push felipeamendes/multi-nginx
  - docker push felipeamendes/multi-server
  - docker push felipeamendes/multi-worker